apiVersion: skaffold/v1beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mikelear/spring-retail-client-app:{{.VERSION}}"
  artifacts:
  - image: changeme
    context: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mikelear/spring-retail-client-app:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: spring-retail-client-app
        chartPath: charts/spring-retail-client-app
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mikelear/spring-retail-client-app"
          image.tag: "{{.DIGEST_HEX}}"
